# Generated by Django 5.1.3 on 2025-05-06 12:35

import api_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=api_app.models.get_file_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=api_app.models.get_file_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
